### ISSUE TITLE
Feature request:  move modal definition to the open method. 

### ISSUE THREAD

**Issue by nihlton** [mpontus/react-modal-hook#27]
the internal plumbing of this hook is interesting - but the end result isn't terribly different from 
```
[modalOpen, setModalOpen] = useState()
```

a more interesting interface would accept the component definition in the open method.

bonus points if the open method returns a promise which the close method resolves.

maybe be something like:

```
import { Prompt, Confirm, Alert } from '/common-modals'
import { delete, rename } from '/person-api'
import { ERROR, SUCCESS } from '/themes'

function Person (props) {
  const { id, name } = props
  [ open, close ] = useModal()

  const handleDelete = () => {
    open(<Confirm msg='are you sure?' close={close} />)
      .then(result => result && delete(id))
      .then(() => open(<Alert msg='deleted!' theme={SUCCESS} close={close}  />))
      .catch(e => open(<Alert msg={e} theme={ERROR} close={close} />))
  }

  const handleRename =() => {
    open(<Prompt msg='New Name' close={close} />)
      .then(result => result && rename(id, result))
      .then(() => open(<Alert msg='renamed!' theme={SUCCESS} close={close} />))
      .catch(e => open(<Alert msg={e} theme={ERROR} close={close} />))
  }

  const handleAward=() => {
    fetch('/random-prize').then(prize => {
      open(<Alert message=`${name} has been awarded ${prize}` open={open}  theme={SUCCESS}  />)
    })
  }

 return <div>
  {name}
  <button onClick={handleDelete} >delete</button>
  <button onClick={handleRename} >rename</button>
  <button onClick={handleAward} >award</button>
}
```

Im sure you could begin to imagine what an implementation like the above would look like with the existing syntax... many state variables, and complex ternary operators in the returned JSX...

**Comment by mpontus** [comment]
Hello, @nihlton and thank you for your input.

> the internal plumbing of this hook is interesting - but the end result isn't terribly different from
> 
> ```
> [modalOpen, setModalOpen] = useState()
> ```

This is exactly what I was trying to address in this library. I tried to abstract this logic, which is common to all use cases involving modals, with or without this library, because of how React works. This library provides minimal abstractions to hide the boolean state and expose more intuitive API for operating the modal state.

The API change that you propose aims to handle a use case that is outside of the scope of this library. If the user wants to use promises or observables as the means of getting results from the modal, more power to them, you can capture anything in a modal closure and pass it in JSX attributes. I don't want to encourage any particular pattern to keep only what's universally useful in the API.
